### ISSUE TITLE
Quality-of-Life

### ISSUE THREAD

**Issue by vito** [concourse/design-notes#18]
* [x] concourse/concourse#243 Favicon should reflect build status
* [ ] concourse/concourse#640 Favicon should reflect pipeline status
* [ ] concourse/atc#28 404 page
